### PR TITLE
100 clear after load

### PR DESCRIPTION
**Pull request by yixiangyin**
# Pull Request Details

## What issue does this PR address

add the reset function for in the dataset button

- Link to associated issue: #105 

## Checklist

Complete the check-list below to ensure your branch is ready for PR.

Flutter Style Guide: https://survivor.togaware.com/gnulinux/flutter-style.html

- [ ] Screenshots included in linked issue
- [ ] Changes adhere to the style and coding guideline
- [ ] No confidential information
- [ ] No duplicated content
- [ ] No lint check errors related to your changes (`make prep` or `flutter analyze lib`)
- [x] Pre-exisiting lint errors noted: 
⚠ unused file: /Users/yinyixiang/repo/my_rattleng/lib/features/model/wordcloud/save_png.dart
- [x] Tested on at least one device
  - [ ] Android Phone
  - [ ] Android Emulator
  - [ ] Chrome on Android
  - [ ] Chrome
  - [ ] iOS
  - [ ] Linux
  - [x] MacOS
  - [ ] Windows
- [x] Added a reviewer

## Finalising

Once PR discussion is complete and reviewer has approved:

- [ ] Merge dev into the branch
- [ ] Resolve any conflicts
- [ ] Add one line summary into CHANGELOG.md
- [ ] Bump appropriate version number in pubspec.yaml
- [ ] Push to git repository and review
- [ ] Merge PR into dev (gjwgit)

### CODE REVIEW

**Review by gjwgit — COMMENTED** [review]
- [x] On first load I should not be prompted to be warned that it will reset the app - it is already in the "reset" state.
- [x] After I load a new dataset the wordcloud is still displayed?

**Review by gjwgit — COMMENTED** [review]
- [x] I think it would be good to have the reset function in a separate file. It will be extended often as we build rattleng. Probably belongs in utils/reset.dart or something like that.

**Review by gjwgit — COMMENTED** [review]
In the PR template  the **No lint check errors related to your changes (make prep or flutter analyze lib)** should be checked after the commands have been run to make sure there are no issues:

I ran `flutter analyze lib` to identify issues:


```
flutter analyze lib
Analyzing lib...                                                

warning • Unused import: 'dart:io' • lib/features/dataset/button.dart:26:8 • unused_import
warning • Unused import: 'package:provider/provider.dart' • lib/features/dataset/button.dart:30:8 • unused_import
   info • The variable name 'LOADED' isn't a lowerCamelCase identifier • lib/features/dataset/button.dart:36:6 • non_constant_identifier_names
warning • Unused import: 'package:rattle/features/model/wordcloud/save_png.dart' • lib/features/model/wordcloud/tab.dart:13:8 • unused_import

4 issues found. (ran in 2.2s)
```

and then ` dart fix --apply lib` to fix them up

```
dart fix --apply lib
Computing fixes in lib...
Applying fixes...

features/dataset/button.dart
  unused_import - 2 fixes

features/model/wordcloud/tab.dart
  unused_import - 1 fix

3 fixes made in 2 files.
```

And also `dart format lib/` to auto format to our style

```
dart format lib/
Formatted lib/features/dataset/button.dart
Formatted lib/home.dart
Formatted 77 files (2 changed) in 0.34 seconds.
```

**Comment by gjwgit** [comment]
- [ ] I am also seeing these issues from 

`dart run dart_code_metrics:metrics check-unused-code --disable-sunset-warning lib` 

and 

`dart run dart_code_metrics:metrics check-unused-files --disable-sunset-warning lib`

```
------------------------------------------------------------------------

Dart Code Metrics: UNUSED CODE
dart run dart_code_metrics:metrics check-unused-code --disable-sunset-warning lib
✔ Analysis is completed. Preparing the results: 2.1s

lib/features/model/wordcloud/save_png.dart:
    ⚠ unused class WordCloudSaveButton
      at /home/gjw/git/github/yixiangyin/rattleng/lib/features/model/wordcloud/save_png.dart:7:1

✖ total unused code (classes, functions, variables, extensions, enums, mixins and type aliases) - 1
make: [support/flutter.mk:164: unused_code] Error 1 (ignored)

------------------------------------------------------------------------

Dart Code Metrics: UNUSED FILES
dart run dart_code_metrics:metrics check-unused-files --disable-sunset-warning lib
✔ Analysis is completed. Preparing the results: 2.1s

⚠ unused file: /home/gjw/git/github/yixiangyin/rattleng/lib/features/model/wordcloud/save_png.dart

✖ total unused files - 1
make: [support/flutter.mk:170: unused_files] Error 1 (ignored)

------------------------------------------------------------------------
```

**Review by gjwgit — COMMENTED** [review]
- [x] Could you also add the `reset` to the button at the top right with the autorenew icon as the callback. Thanks.

**Comment by yixiangyin** [comment]
> * [ ]  I am also seeing these issues from
> 
> 
> `dart run dart_code_metrics:metrics check-unused-code --disable-sunset-warning lib`
> 
> and
> 
> `dart run dart_code_metrics:metrics check-unused-files --disable-sunset-warning lib`
> 
> ```
> ------------------------------------------------------------------------
> 
> Dart Code Metrics: UNUSED CODE
> dart run dart_code_metrics:metrics check-unused-code --disable-sunset-warning lib
> ✔ Analysis is completed. Preparing the results: 2.1s
> 
> lib/features/model/wordcloud/save_png.dart:
>     ⚠ unused class WordCloudSaveButton
>       at /home/gjw/git/github/yixiangyin/rattleng/lib/features/model/wordcloud/save_png.dart:7:1
> 
> ✖ total unused code (classes, functions, variables, extensions, enums, mixins and type aliases) - 1
> make: [support/flutter.mk:164: unused_code] Error 1 (ignored)
> 
> ------------------------------------------------------------------------
> 
> Dart Code Metrics: UNUSED FILES
> dart run dart_code_metrics:metrics check-unused-files --disable-sunset-warning lib
> ✔ Analysis is completed. Preparing the results: 2.1s
> 
> ⚠ unused file: /home/gjw/git/github/yixiangyin/rattleng/lib/features/model/wordcloud/save_png.dart
> 
> ✖ total unused files - 1
> make: [support/flutter.mk:170: unused_files] Error 1 (ignored)
> 
> ------------------------------------------------------------------------
> ```

This happens because the save button is commented out.

**Comment by yixiangyin** [comment]
- [ ] add authorship

**Comment by gjwgit** [comment]
> > * [ ]   I am also seeing these issues from
> > 
> > `dart run dart_code_metrics:metrics check-unused-code --disable-sunset-warning lib`
> > and
> > `dart run dart_code_metrics:metrics check-unused-files --disable-sunset-warning lib`
> > ```
> > ------------------------------------------------------------------------
> > 
> > Dart Code Metrics: UNUSED CODE
> > dart run dart_code_metrics:metrics check-unused-code --disable-sunset-warning lib
> > ✔ Analysis is completed. Preparing the results: 2.1s
> > 
> > lib/features/model/wordcloud/save_png.dart:
> >     ⚠ unused class WordCloudSaveButton
> >       at /home/gjw/git/github/yixiangyin/rattleng/lib/features/model/wordcloud/save_png.dart:7:1
> > 
> > ✖ total unused code (classes, functions, variables, extensions, enums, mixins and type aliases) - 1
> > make: [support/flutter.mk:164: unused_code] Error 1 (ignored)
> > 
> > ------------------------------------------------------------------------
> > 
> > Dart Code Metrics: UNUSED FILES
> > dart run dart_code_metrics:metrics check-unused-files --disable-sunset-warning lib
> > ✔ Analysis is completed. Preparing the results: 2.1s
> > 
> > ⚠ unused file: /home/gjw/git/github/yixiangyin/rattleng/lib/features/model/wordcloud/save_png.dart
> > 
> > ✖ total unused files - 1
> > make: [support/flutter.mk:170: unused_files] Error 1 (ignored)
> > 
> > ------------------------------------------------------------------------
> > ```
> 
> This happens because the save button is commented out. Thanks I have put that in the pr description.

Ignore for now.

**Review by gjwgit — APPROVED** [review]

**Pull request merged**
